backend/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.home, name='home'),
	path('genetic-tests/', views.gen_test, name='gen_test'),
	path('genetic-test/<slug:slug>/', views.sub_category, name='info'),
	path('service/<int:pk>/', views.service, name='service'),
	path('contacts/', views.contacts, name='contacts'),
	path('search/', views.search, name='search'),
	path('accessories/', views.accessories, name='accessories'),
	path('certificates/', views.certificates, name='certificates'),
	path('partners/', views.partners, name='partners'),
]

gen_lab/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from django.shortcuts import render_to_response
from django.template import RequestContext


def handler404(request, exception, template_name="404.html"):
    response = render_to_response(template_name)
    response.status_code = 404
    return response


urlpatterns = i18n_patterns(
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    path('gjalub-ad-aslnbmjs$asdykf6yg3asdasd/', admin.site.urls),
    path('', include('backend.main.urls', namespace='main')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

admin.site.site_header = "Ultragenom Admin"
admin.site.site_title = "Ultragenom Admin Portal"
admin.site.index_title = "Ultragenom"

backend/main/views.py
from django.shortcuts import render, redirect
from .models import Category, SubCategory, SubSubCategory, Service, Form
from django.http import JsonResponse
from django.conf import settings
from .sendgrid_mail import SendGridMail

from backend.static_contact.models import Accessories, CertificateText


# Create your views here.


def home(request):
    ctx = {}
    ctx['home_page'] = True
    accessories = Accessories.objects.all()
    acc_list = []
    # for acc in accessories:
    #     print('acc', acc)
    #     acc_list.append({
    #         'acc': acc,
    #         'photos': acc.get_photos()
    #     })
    ctx['acc_list'] = accessories
    ctx['text'] = CertificateText.objects.first()
    return render(request, 'main/home.html', ctx)


def gen_test(request):
    ctx = {}
    ctx['category'] = Category.objects.all()
    return render(request, 'main/gen_test.html', ctx)


def sub_category(request, slug):
    ctx = {}
    sub_cat = SubSubCategory.objects.get(slug=slug)
    ctx['info'] = sub_cat
    return render(request, 'main/category.html', ctx)


def service(request, pk):
    ctx = {}
    ctx['service'] = Service.objects.get(pk=pk)
    return render(request, 'main/service.html', ctx)


def contacts(request):
    ctx = {}
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        msg = request.POST.get('msg')
        form = Form.objects.create(name=name, phone=phone, email=email, msg=msg)
        message_from_client = """
Номер телефону : {phone} <br>\n
Ім'я: {name}<br>\n
Email: {email}<br>\n
Повідомлення: {msg}<br>\n
"""
        str_ = message_from_client.format(phone=phone, name=name, email=email, msg=msg)
        send_grid = SendGridMail(
            subject='Повідомлення з сайту ultragenom.com',
            content=str_
        )
        try:
            response = send_grid.send_()
        except Exception as e:
            print(type(e), e)
        return JsonResponse({'status': True})
    return render(request, 'main/contacts.html', ctx)


def search(request):
    ctx = {}
    q = request.GET.get('query')
    if not q:
        return redirect('main:gen_test')
    if len(q.split()) == 1:
        q = q.strip().lower()
    else:
        q = q.lower()
    result_by_sub_sub_cat = SubSubCategory.objects.filter(tags__tag__icontains=q)
    list_category = []
    for category in Category.objects.all():
        lower_case_list_name = [name.lower() for name in
                                [category.name or '', category.name_ru or '', category.name_uk or '',
                                 category.name_en or '']]
        for name_lower in lower_case_list_name:
            if q in name_lower:
                list_category.append(category)

    list_subcategory = []
    for category in SubCategory.objects.all():
        lower_case_list_name = [name.lower() for name in
                                [category.name or '', category.name_ru or '', category.name_uk or '',
                                 category.name_en or '']]
        for name_lower in lower_case_list_name:
            if q in name_lower:
                list_subcategory.append(category)

    list_analys_by_name = []
    for analys in SubSubCategory.objects.all():
        lower_case_list_name = [name.lower() for name in
                                [analys.name or '', analys.name_ru or '', analys.name_uk or '', analys.name_en or '']]
        for name_lower in lower_case_list_name:
            if q in name_lower:
                list_analys_by_name.append(analys)

    # result_by_sub_sub_cat = None
    result_by_sub_category = list(set(list_subcategory))
    result_by_category = list(set(list_category))
    if result_by_sub_sub_cat:
        print('if!!!!!')
        if list_analys_by_name:
            print('if-if!!!!!!!')
            result_by_sub_sub_cat = list(set(list(result_by_sub_sub_cat) + list(set(list_analys_by_name))))
        else:
            print('result_by_sub_sub_cat', result_by_sub_sub_cat)
            result_by_sub_sub_cat = list(set(list(result_by_sub_sub_cat)))
        ctx['result_by_sub_sub_cat'] = result_by_sub_sub_cat
    else:
        print('ELS!!!!')
        result_by_sub_sub_cat = list(list(set(list_analys_by_name)))
        ctx['result_by_sub_sub_cat'] = result_by_sub_sub_cat

    anal_in_category = [analys for analys in result_by_sub_sub_cat if analys.category]
    anal_in_sub_category = [analys for analys in result_by_sub_sub_cat if analys.subcategory]
    ctx['result_by_sub_category'] = result_by_sub_category
    ctx['result_by_category'] = result_by_category
    ctx['search'] = True
    ctx['q'] = q
    ctx['anal_in_category'] = anal_in_category
    ctx['anal_in_sub_category'] = anal_in_sub_category
    list_response = []
    for c in result_by_category:
        new_obj = {'category': {'name': c.name, 'list_analys': c.get_sub_sub_cat(), 'subcat_list': [{
            'subcat': {
                'name': elem.name,
                'list_': list(elem.get_sub_sub_cat())
            }
        } for elem in c.get_sub_cat()]}}

        list_response.append(new_obj)
    for sc in result_by_sub_category:
        new_obj = {'category': {'name': None, 'list_analys': [], 'subcat_list': []}}
        new_sub_obj = {'subcat': {'name': '', 'list_': []}}
        status = False
        for l in list_response:
            if l['category']['name'] == sc.category.name:
                status = True
        if not status:
            new_obj['category']['name'] = sc.category.name
            new_sub_obj['subcat']['name'] = sc.name
            new_sub_obj['subcat']['list_'].append(sc.get_sub_sub_cat())
            # new_obj['category']['subcat_list'].append(new_sub_obj)
            new_obj['category']['subcat_list'] = [{
                'subcat': {
                    'name': sc.name,
                    'list_': list(sc.get_sub_sub_cat())
                }
            }]
            list_response.append(new_obj)

    for elem in anal_in_category:
        new_obj = {
            'category': {
                'name': None,
                'list_analys': [],
                'subcat_list': []
            }
        }
        status = False
        for l in list_response:
            if l['category']['name'] == elem.category.name:
                old_list = list(l['category']['list_analys'])
                old_list.append(elem)
                new_obj['category']['list_analys'] = old_list
                status = True
        if not status:
            new_obj['category']['name'] = elem.category.name
            old_list = new_obj['category']['list_analys']
            old_list.append(elem)
            new_obj['category']['list_analys'] = old_list
            list_response.append(new_obj)

    for a in anal_in_sub_category:
        new_sub_obj = {
            'subcat': {
                'name': '',
                'list_': []
            }
        }
        status = False
        for l in list_response:
            sub = False
            if l['category']['name'] == a.subcategory.category.name:
                for s in l['category']['subcat_list']:
                    if s['subcat']['name'] == a.subcategory.name:
                        s['subcat']['list_'].append(a)
                        sub = True
                if not sub:
                    new_sub_obj['subcat']['name'] = a.subcategory.name
                    new_sub_obj['subcat']['list_'].append(a)
                    l['category']['subcat_list'].append(new_sub_obj)

    for l in list_response:
        old_list = l['category']['list_analys']
        l['category']['list_analys'] = list(set(old_list))
        for elem in l['category']['subcat_list']:
            subcat_old = elem['subcat']['list_']
            elem['subcat']['list_'] = list(set(subcat_old))

    ctx['list_response'] = list_response
    return render(request, 'main/gen_test.html', ctx)


def accessories(request):
    ctx = {}
    accessories = Accessories.objects.all()
    acc_list  = []
    # for acc in accessories:
    #     print('acc' , acc)
    #     acc_list.append({
    #         'acc': acc,
    #         'photos': acc.get_photos()
    #     })
    # photos = accessories.get_photos()
    # ctx['accessories'] = accessories
    # ctx['photos'] = photos if len(photos) > 1 else photos[0]
    # ctx['len_photos'] = len(photos)
    ctx['acc_list'] = accessories
    return render(request, 'main/accessories.html', ctx)


def certificates(request):
    ctx = {}
    ctx['text'] = CertificateText.objects.first()
    return render(request, 'main/certificates.html', ctx)

def partners(request):
    ctx = {}
    ctx['text'] = CertificateText.objects.first()
    return render(request, 'main/partners.html', ctx)

templates/main/accessories.html
{% extends 'index.html' %}

{% load i18n %}
{% load poll_extras %}

{% block content %}
<div class="container block-margin">
    {% if acc_list|length > 0 %}
    <h2 class="info-name">{% trans 'Наше обладнання' %}</h2>
    <div class="accessories-img-container">
        {% if acc_list|length > 1 %}

        <div class="swiper-container accessories-swiper">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                {% for acc in acc_list %}
                <div class="swiper-slide">
                    <img class="accessories-img" src="{{acc.image.url}}">
                </div>
                {% endfor %}
            </div>
        </div>
        {% else %}
        {% with photo=acc_list|first %}
        <img class="accessories-img" src="{{photo.image.url}}">
        {% endwith %}
        {% endif %}
        <div class="swiper-pagination accessories-pagination"></div>
    </div>
    {% endif %}
</div>
{% endblock %}
{% block js %}
<script>
    App.accessories_page.init();
</script>
{% endblock  %}

templates/main/category.html
{% extends 'index.html' %}

{% load i18n %}

{% block content %}
<div class="container analysis-container block-margin">
<!--    <h1 class="title-info-page">{% trans 'Гени' %}</h1>-->
    <h2 class="info-name">{{ info.name }}</h2>
    <div class="genetic-analysis-container">
        {% for key_value in info.get_key_values %}
        <div class="key-value-wrap">
            <div class="name-column-container">
                <div class="name-content">
                    {{ key_value.key }}
                </div>
            </div>
            <div class="value-column-container">
                <div class="value-content">
                    {{ key_value.value }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if info.text %}
    <div class="info-text">
        {{ info.text|safe }}
    </div>
    {% endif %}
</div>


{% endblock %}

templates/main/certificates.html
{% extends 'index.html' %}

{% load i18n %}
{% load poll_extras %}

{% block content %}
{% get_license as cert %}
<div class="container block-margin">
    {% for elem in cert %}
    <h2 class="info-name">{{ elem.license }}</h2>
        {% if elem.image %}
            <div class="certificate-img-container">
                <a target="_blank" href="{{elem.image.url}}">
                    <img width="250" height="400" src="{{ elem.image.url }}" alt="certificate">
                </a>
            </div>
        {% endif %}
    {% endfor %}
    <div class="quality-control-container">
        <h2 class="info-name">{{ text.title }}</h2>
        <div>
            {{ text.text | safe }}
        </div>
    </div>
</div>

{% endblock %}

templates/main/contacts.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% load poll_extras %}

{% block content %}
{% get_phones  as phones %}
{% get_emails  as emails %}
{% get_social  as social %}
{% get_address  as address %}

<div class="container block-margin">
    <h2 class="contacts-page-title">{% trans 'Контакти' %}</h2>
    <div class="contacts-page-container">
        <div class="contacts-page-info-container">
            {% if phones %}
            <div class="contacts-block">
                <h4 class="contacts-title">{% trans 'Контактний телефон' %}</h4>
                {% for phone in phones %}
                <div class="contacts-content">
                    <img src="{% static 'images/contacts/phone.svg' %}">
                    <a href="tel:{{phone.phone}}">{{phone.phone}}</a>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% if emails %}
            <div class="contacts-block">
                <h4 class="contacts-title">Email</h4>
                {% for email in emails %}
                <div class="contacts-content">
                    <img src="{% static 'images/contacts/mail.svg' %}">
                    <a href="mailto:{{email.email}}">{{email.email}}</a>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% if social %}
            <div class="contacts-block">
                <h4 class="contacts-title">{% trans 'Ми у соцмережах' %}</h4>
                {% for soc in social %}
                <div class="contacts-content">
                     {% if soc.icon %}
                        <img src="{{soc.icon.url}}">
                    {% else %}
                        <img src="{% static 'images/contacts/web.svg' %}">
                    {% endif %}
                        <a href="{{soc.link}}" target="_blank">{{soc.name}}</a>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% if address %}
            <div class="contacts-block">
                <h4 class="contacts-title">{% trans 'Адреса' %}</h4>
                {% for addr in address %}
                <div class="contacts-content">
                    <img src="{% static 'images/contacts/pin.svg' %}">
                    <a href="https://goo.gl/maps/1FNc7BCHiMa3Lbx39" target="_blank">{{addr.address}}</a>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="contacts-page-form-container">
            <h4 class="contact-us-title">{% trans 'Напишіть нам' %}</h4>
            <form class="contacts-form" action="{% url 'main:contacts' %}" id="js_form_ajax" method="post"> {% csrf_token %}
                <div class="form-group" id="name-form">
                    <label for="">{% trans 'Прізвище та ім’я' %}</label>
                    <input placeholder="{% trans 'Прізвище та ім’я' %}" type="text" name="name" onkeyup="App.checkInput(this, ['name-empty', 'name-error'])">
                </div>
                <div class="error-form" id="name-empty">{% trans 'Пусте поле' %}</div>
                <div class="error-form" id="name-error">{% trans "Ім'я не валідне" %}</div>
                <div class="form-group" id="phone-form">
                    <label for="">{% trans 'Контактний телефон' %}</label>
                    <input placeholder="{% trans 'Контактний телефон' %}" type="text" name="phone" onkeyup="App.checkInput(this, ['phone-error', 'phone-empty'])">
                </div>
                <div class="error-form" id="phone-empty">{% trans 'Пусте поле' %}</div>
                <div class="error-form" id="phone-error">{% trans 'Телефон не валідний' %}</div>
                <div class="form-group" id="email-form">
                    <label for="">{% trans 'Email' %}</label>
                    <input placeholder="{% trans 'Email' %}" type="text" name="email" onkeyup="App.checkInput(this, ['email-empty', 'email-error'])">
                </div>
                <div class="error-form" id="email-empty">{% trans 'Пусте поле' %}</div>
                <div class="error-form" id="email-error">{% trans 'Email не валідний' %}</div>
                <div class="form-group">
                    <label for="">{% trans 'Повідомлення' %}</label>
                    <textarea placeholder="{% trans 'Повідомлення' %}" name="msg" id="" cols="30" rows="10"></textarea>
                </div>
                <button class="send-form-button">{% trans 'Надіслати' %}</button>
            </form>
        </div>
    </div>
    <div class="contacts-page-map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2538.314892168103!2d30.473346051169564!3d50.49109687938032!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4cdf26f2e2f43%3A0x9231d3adeb188b86!2z0JrRg9GA0LXQvdGW0LLRgdGM0LrQuNC5INC_0YDQvtCy0YPQu9C-0LosIDE3LCDQmtC40ZfQsiwgMDIwMDA!5e0!3m2!1suk!2sua!4v1590605714770!5m2!1suk!2sua" width="800" height="600" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
</div>
<!-- The Modal -->
<div id="modal-success">
    <!-- Modal content -->
    <div class="modal-content">
        <span class="close" onclick="App.closeSuccessModal()">&times;</span>
        <p class="modal-message">{% trans 'Форма успішно відправлена' %}</p>
        <button class="modal-button" onclick="App.closeSuccessModal()">Ок</button>
    </div>
</div>
{% endblock content %}

{% block js %}
<script>
    App.callBackForm();
</script>
{% endblock js %}

templates/main/gen_test.html
{% extends 'index.html' %}
{% load i18n %}

{% block content %}
<div class="container gen-page-container block-margin">
<!--        <h1 class="title-section"> {% trans 'Гени' %}</h1>-->
        <div class="search-form">
            <div class="animation-container">
                <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
                <lottie-player src="https://assets1.lottiefiles.com/datafiles/QNPjM6wN83nuep8/data.json"  background="transparent"  speed="1"  style="width: 260px; height: 160px;" loop autoplay></lottie-player>
            </div>
            <div class="form-container">
                <form class="form" action="{% url 'main:search' %}">
                    <div class="field">

                        <input type="text" name="query" class="input-search" maxlength="100" {% if q %} value="{{q}}" {% endif %} id="fullname" placeholder=" ">
                        <label for="fullname">{% trans 'Пошук по генам' %}</label>

                    </div>
                    <button class="search-button">{% trans 'Пошук' %}</button>
                </form>
            </div>
        </div>
        {% for cat in category %}
        <div class="category-container">

            <h2 class="category-title">{{cat.name}}</h2>
            {% if cat.get_sub_cat %}
            {% for sub_cat in cat.get_sub_cat %}
            <div class="sub-category-container">
                {% if not sub_cat.get_sub_sub_cat %}
                <a class="sub-cat-title no-arrow"
                   href="#">{{ sub_cat.name }}</a>
                {% else %}
                <h4 class="js-sub-cat sub-cat-title open" data-cat-id="sub_cat_{{sub_cat.id}}">{{ sub_cat.name }}</h4>
                <div class="sub-menu hide" data-menu="sub_cat_{{sub_cat.id}}">
                    {% for sub_sub_cat in sub_cat.get_sub_sub_cat %}
                    <div class="genetic-analysis-subcategory-container">
                        <a class="genetic-analysis no-arrow decor-dot"
                           href="{% url 'main:info'  slug=sub_sub_cat.slug  %}">{{ sub_sub_cat.name }}</a>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% for sub_cat in cat.get_sub_sub_cat %}
                   <a class="genetic-analysis  no-arrow decor-dot"
                           href="{% url 'main:info'  slug=sub_cat.slug  %}">{{ sub_cat.name }}</a>
            {% endfor %}
        </div>

    {% endfor %}

    {% for l in list_response %}
    <h2 class="category-title">{{l.category.name}}</h2>
    <div class="sub-category-container">
    {% for sub in l.category.subcat_list %}
     <h4 class="js-sub-cat sub-cat-title " data-cat-id="sub_cat_{{forloop.counter}}">{{ sub.subcat.name }}</h4>
        <div class="sub-menu " data-menu="sub_cat_{{forloop.counter}}">
            {% for anal in sub.subcat.list_ %}
                <a class="genetic-analysis no-arrow decor-dot"  href="{% url 'main:info'  slug=anal.slug  %}">{{ anal.name }}</a>
            {% endfor %}
        </div>
    {% endfor %}
    </div>
    <br>
        {% for anal in l.category.list_analys %}
            <a class="genetic-analysis  no-arrow decor-dot"
                           href="{% url 'main:info'  slug=anal.slug  %}">{{ anal.name }}</a>
        {% endfor %}

    {% endfor %}

    {% if not list_response  and search %}
    <div class="no-results">{% trans 'Нічого не знайдено' %}</div>
    {% endif %}
</div>
{% endblock %}

{% block js %}
<script>
    App.info_page.init();
</script>
{% endblock  %}

templates/main/home.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% load poll_extras %}
{% block content %}


<div class="main-background">
    <div class="main-content container">
        <h1 class="main-title">Ultragenom</h1>
        <div class="main-text">
            {% blocktrans %}
            Ми надаємо лікарям та їх пацієнтам всебічні та якісні інструменти та ресурси для генетичної діагностики.
            Роблячи це, ми надаємо можливості для цілеспрямованого лікування та індивідуальної допомоги пацієнтам.
            {% endblocktrans %}
        </div>
    </div>
</div>
<section class="our-services-container container">
    {% get_services as services %}
    {% get_license as cert %}
    <h2 class="title" id="service">{% trans 'Наші послуги' %}</h2>
    <div class="our-services">
        {% for service in services %}
        <div class="service">
            <div class="service-content">
                {% if service.icon %}
                <img class="service-img" src="{{service.icon.url}}">
                {% else %}
                <img class="service-img" src="{% static 'img/services/service-1.svg' %}">
                {% endif %}
                <div class="service-text">
                    {{service.lead}}
                </div>
            </div>
            <a href="{% url 'main:service' pk=service.id %}" class="service-read-more">{% trans 'Читати більше' %}</a>
        </div>
        {% endfor %}
    </div>
</section>
{% get_about as about_block %}
<div class="main-page-background">
    <section class="about-us-container container">
        <h2 class="title" id="about-us">{% trans 'Про нас' %}</h2>
        {% for about in about_block %}
        <div class="about-us-content {{ forloop.counter0 | check_reversed }}">
            <div class="about-us-text">
                {{ about.text|safe }}
            </div>
            <div class="about-us-img-container">
                <img src="{{about.image.url}}">
            </div>
        </div>
        {% endfor %}




    </section>
    <section class="team-container container">
        <h2 class="title" id="team">{% trans 'Наша команда' %}</h2>
        <div class="team-description">{% trans 'текст про команду' %}</div>
        {% get_team as team_members %}
        <div class="team-member-container">
            {% for member in team_members %}
            <div class="team-member">
                <div class="team-photo-container">
                    <img src="{{ member.photo.url }}">
                </div>
                <div class="team-member-content">
                    <div class="team-member-name">
                        {{ member.name }}
                    </div>
                    <div class="team-member-description">
                        {{ member.occupation }}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    {% if acc_list|length > 0 %}
    <section class="accessories-main-page-container container">

        <h2 class="title" id="accessories">{% trans 'Наше обладнання' %}</h2>
        <div class="accessories-img-container">
            {% if acc_list|length > 1 %}

            <div class="swiper-container accessories-swiper">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper">
                    <!-- Slides -->
                    {% for acc in acc_list %}
                    <div class="swiper-slide accessories-slide">
                        <img class="accessories-img" src="{{acc.image.url}}">
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% else %}
            {% with photo=acc_list|first %}
            <img class="accessories-img" src="{{photo.image.url}}">
            {% endwith %}
            {% endif %}
            <div class="swiper-pagination accessories-pagination"></div>

        </div>

    </section>
    {% endif %}
    {% if cert|length > 0 %}
    <section class="certificate-main-page-container container">
        <h2 class="title" id="certificates">{% trans 'Наші сертифікати' %}</h2>
        {% for elem in cert %}
        <h2 class="info-name">{{ elem.license }}</h2>
        {% if elem.image %}
        <div class="certificate-img-container">
            <a target="_blank" href="{{elem.image.url}}">
                <img width="250" height="400" src="{{ elem.image.url }}" alt="certificate">
            </a>
        </div>
        {% endif %}
        {% endfor %}
    </section>
    {% endif %}
    <div class="quality-control-container container">
        <h2 class="info-name">{{ text.title }}</h2>
        <div class="quality-content">{{ text.text | safe }}</div>
    </div>
    {% get_partners as partners %}
    {% if partners|length > 0 %}
    <section class="our-partners-main-page-container container">
        <h2 class="title" id="partners">{% trans 'Наші партнери' %}</h2>
        <div class="swiper-container partners-swiper">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                {% for par in partners %}
                <div class="swiper-slide">
                    <h2 class="partner-title">
                        {% if par.img %}
                        <a href="{{par.link}}" target="_blank">
                            <img width="100" src="{{ par.img.url }}" alt="partner">
                            <span style="color: #1f3f68;">{{ par.title }}</span>
                        </a>
                        {% else %}
                        <a href="{{par.link}}" target="_blank">
                            <span style="color: #1f3f68;">{{ par.title }}</span>
                        </a>
                        {% endif %}
                    </h2>

                    <div class="partner-content-container">
                        {% if par.photo %}
                        <div class="partner-img-container">
                            <img class="partner-img" src="{{ par.photo.url }}" alt="partner-image">
                        </div>
                        <div class="partner-text-container">
                            {{par.text | safe}}
                        </div>
                        {% else %}
                        <div class="partner-text-container-full-width">
                            {{par.text | safe}}
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="swiper-pagination partners-pagination"></div>
    </section>
    {% endif %}
    <section class="feedback-container">
        <div class="container">
            {% get_reviews as reviews %}
            {% if reviews %}
            <h2 class="title" id="feedbacks">{% trans 'Відгуки' %}</h2>
            <div class="swiper-container feedback-swiper-container">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper">
                    <!-- Slides -->
                    {% for rev in reviews %}
                    <div class="swiper-slide">
                        <div class="feedback-content-container">
                            <div class="feedback-title">
                                <div class="feedback-img">
                                    <img src="{{rev.photo.url}}" width="60" height="60" style="border-radius: 50%;">
                                </div>
                                <div class="feedback-name">
                                    {{rev.name}}
                                </div>
                            </div>
                            <div class="feedback-text">
                                {{rev.text}}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- If we need pagination -->
            </div>
            <div class="swiper-pagination feedback-pagination"></div>
            {% endif %}
        </div>
    </section>
</div>
{% endblock %}

{% block js %}
<script>
    App.initFeedbackSwiper();
    App.accessories_page.init();
    App.partners_page.init();
</script>
{% endblock %}

templates/main/partners.html
{% extends 'index.html' %}

{% load i18n %}
{% load poll_extras %}

{% block content %}
{% get_partners  as partners %}
<div class="container block-margin">

    {% for par in partners %}
    <h2 class="info-name">
        {% if par.img %}
        <a href="{{par.link}}" target="_blank">
            <img width="50" height="50" src="{{ par.img.url }}" alt="">
            <span style="color: #1f3f68;">{{ par.title }}</span>
        </a>
        {% endif %}
    </h2>
    <div class="about-us-content reversed">
        <div class="about-us-text">
            {{par.text | safe}}
        </div>
        {% if par.photo %}
        <div class="about-us-img-container">
            <img class="partner-img" src="{{ par.photo.url }}" alt="">
        </div>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock  %}