backend/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.home, name='home'),
	path('genetic-tests/', views.gen_test, name='gen_test'),
	path('genetic-test/<slug:slug>/', views.sub_category, name='info'),
	path('service/<int:pk>/', views.service, name='service'),
	path('contacts/', views.contacts, name='contacts'),
	path('search/', views.search, name='search'),
	path('accessories/', views.accessories, name='accessories'),
	path('certificates/', views.certificates, name='certificates'),
	path('partners/', views.partners, name='partners'),
]

gen_lab/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from django.shortcuts import render_to_response
from django.template import RequestContext


def handler404(request, exception, template_name="404.html"):
    response = render_to_response(template_name)
    response.status_code = 404
    return response


urlpatterns = i18n_patterns(
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    path('gjalub-ad-aslnbmjs$asdykf6yg3asdasd/', admin.site.urls),
    path('', include('backend.main.urls', namespace='main')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

admin.site.site_header = "Ultragenom Admin"
admin.site.site_title = "Ultragenom Admin Portal"
admin.site.index_title = "Ultragenom"

templates/includes/footer.html
{% load poll_extras %}
{% load i18n %}
{% load static %}

{% get_language request as language %}
{% get_phones  as phones %}
{% get_emails  as emails %}
{% get_social  as social %}
{% get_address  as address %}
{% get_partners  as partners %}
{% get_license  as licenses %}
<footer class="{% if home_page %}footer-container{% else %}full-footer-width{% endif %}">
    <div class="footer-inner-container">
        {% if home_page %}
        <div class="contacts-container">
            <div class="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2538.314892168103!2d30.473346051169564!3d50.49109687938032!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4cdf26f2e2f43%3A0x9231d3adeb188b86!2z0JrRg9GA0LXQvdGW0LLRgdGM0LrQuNC5INC_0YDQvtCy0YPQu9C-0LosIDE3LCDQmtC40ZfQsiwgMDIwMDA!5e0!3m2!1suk!2sua!4v1590605714770!5m2!1suk!2sua"
                        width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""
                        aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="contacts-panel">
                {% if phones %}
                <div class="contacts-panel-item-container contacts-mobile">
                    <h4 class="contacts-title">{% trans 'Контактний телефон' %}</h4>
                    {% for phone in phones %}
                    <div class="contacts-content">
                        <img src="{% static 'images/contacts/phone.svg' %}">
                        <a href="tel:{{phone.phone}}">{{phone.phone}}</a>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                {% if emails %}
                <div class="contacts-panel-item-container email">
                    <h4 class="contacts-title">Email</h4>
                    {% for email in emails %}
                    <div class="contacts-content">
                        <img src="{% static 'images/contacts/mail.svg' %}">
                        <a href="mailto:{{email.email}}">{{email.email}}</a>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                {% if social %}
                <div class="contacts-panel-item-container social">
                    <h4 class="contacts-title">{% trans 'Ми у соцмережах' %}</h4>
                    {% for soc in social %}
                    <div class="contacts-content">
                        {% if soc.icon %}
                        <img src="{{soc.icon.url}}">
                        {% else %}
                        <img src="{% static 'images/contacts/web.svg' %}">
                        {% endif %}
                        <a href="{{soc.link}}" target="_blank">{{soc.name}}</a>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                {% if address %}
                <div class="contacts-panel-item-container address">
                    <h4 class="contacts-title">{% trans 'Адреса' %}</h4>
                    {% for addr in address %}
                    <div class="contacts-content">
                        <img src="{% static 'images/contacts/pin.svg' %}">
                        <a href="https://goo.gl/maps/1FNc7BCHiMa3Lbx39" target="_blank">{{addr.address}}</a>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="line-footer"></div>
        {% endif %}
        <div class="footer-info-container">
            <div class="footer-partners-info">
                <div class="footer-logo">
                    <a href="{% url 'main:home' %}" style="display: inline-flex; align-items: center;">
                        <img width="100" height="100" src="{% static 'images/logo.png' %}">
                        <div class="logo-name">Ultragenom</div>
                    </a>
                </div>
                {% if partners %}
                <div class="footer-our-partners">
                    <div class="partners-text">{% trans 'Наші партнери:' %}</div>
                    <div class="partners-links">
                        {% for part in partners %}
                        <a href="{{part.link}}" target="_blank">
                            <img alt="Partners link" src="{{part.img.url}}" width="100">
                        </a>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
               <div class="license-container">
                    {% for l in licenses %}
                    <div class="license">
                        <div class="license-text">{{l.license}}</div>
                            {% if l.image %}
                        <a target="_blank" href="{{l.image.url}}">
                                <img class="license-img" width="200px" src="{{ l.image.url }}"
                                     alt="license">
                        </a>
                            {% endif %}
                    </div>
                    {% endfor %}
               </div>
            </div>
            <div class="footer-links">
                <a {% if not home_page %} href=" {% url 'main:home' %}#service " {% endif %}
                   onclick="scrollToAnchor('service')" class="link">{% trans 'Наші послуги' %}</a>
                <a {% if not home_page %} href=" {% url 'main:home' %}#about-us " {% endif %}
                   onclick="scrollToAnchor('about-us')" class="link">{% trans 'Про нас' %}</a>
<!--                <a class="link">{% trans 'Технологічна вітка' %}</a>-->
                <a href="{% url 'main:contacts' %}" class="link">{% trans 'Контакти' %}</a>
                <div class="lang-panel">
                    {% for lang in language.LANGUAGES %}
                    {% if lang.0 == language.SELECTEDLANG %}
                    <button class="lang {% if lang.0 == request.LANGUAGE_CODE %} active {% endif %}">
                        {{ lang.0 }}
                    </button>
                    {% else %}
                    <form action="{% url 'set_language' %}" method="post"> {% csrf_token %}
                        {% if language.redirect_to == '/' %}

                {% if  lang.0 == 'uk' %}
                <input name="next" type="hidden" value="{{ language.redirect_to }}"/>
                {% else %}
                <input name="next" type="hidden" value="/{{lang.0}}"/>

                {% endif %}
                {% endif %}
                        <input type="hidden" name="language" value="{{ lang.0 }}">
                        <button class="lang ">
                            {{ lang.0 }}
                        </button>
                    </form>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="copyright">
                © 2020 Ultragenom.{% trans ' All rights reserved.' %}
            </div>
<!--            <div class="lang-panel">-->
<!--                {% for lang in language.LANGUAGES %}-->
<!--                {% if lang.0 == language.SELECTEDLANG %}-->
<!--                <button class="lang {% if lang.0 == request.LANGUAGE_CODE %} active {% endif %}">-->
<!--                    {{ lang.0 }}-->
<!--                </button>-->
<!--                {% else %}-->
<!--                <form action="{% url 'set_language' %}" method="post"> {% csrf_token %}-->
<!--                    <input name="next" type="hidden" value="{{ language.redirect_to }}"/>-->
<!--                    <input type="hidden" name="language" value="{{ lang.0 }}">-->
<!--                    <button class="lang ">-->
<!--                        {{ lang.0 }}-->
<!--                    </button>-->
<!--                </form>-->
<!--                {% endif %}-->
<!--                {% endfor %}-->
<!--            </div>-->
        </div>
    </div>
</footer>

templates/includes/header.html
{% load poll_extras %}
{% load i18n %}
{% load static %}
{% get_language request as language %}
{% get_license  as license %}
{% get_partners  as partners %}
{% get_accessories  as acc %}
{% get_reviews as reviews %}
<header {% if not home_page %} class="scroll-header js-not-home" {% endif %}>
    <div class="header-container">
        <a href="{% url 'main:home' %}">
            <img width="100" height="100" src="{% static 'images/logo.png' %}">
        </a>
        <div class="nav-links-container">
            <div class="dropdown">
                <button class="dropbtn">{% trans 'Послуги' %}</button>
                <div class="dropdown-content">
                    <a href="{% url 'main:gen_test' %}" class="nav-link">{% trans 'Генетичні тести' %}</a>
                    <!--                    <a href="#" class="nav-link">{% trans 'Інше' %}</a>-->
                </div>
            </div>
            <div class="dropdown">
                <button class="dropbtn">{% trans 'Про нас' %}</button>

                <div class="dropdown-content">
                    <a {% if not home_page %} href=" {% url 'main:home' %}#service " {% endif %}
                       onclick="scrollToAnchor('service')" class="nav-link">{% trans 'Наші послуги' %}</a>
                    <a {% if not home_page %} href=" {% url 'main:home' %}#about-us " {% endif %}
                       onclick="scrollToAnchor('about-us')" class="nav-link">{% trans 'Про нас' %}</a>
                    <a {% if not home_page %} href="{% url 'main:home' %}#team " {% endif %}
                       onclick="scrollToAnchor('team')" class="nav-link">{% trans 'Наша команда' %}</a>
                    {% if acc %}
                    <a {% if not home_page %}href=" {% url 'main:home' %}#accessories " {% endif %}
                       onclick="scrollToAnchor('accessories')" class="nav-link">{% trans 'Наше обладнання' %}</a>
                    {% endif %}
                    {% if license %}
                    <a {% if not home_page %}href=" {% url 'main:home' %}#certificates " {% endif %}
                       onclick="scrollToAnchor('certificates')" class="nav-link">{% trans 'Наші сертифікати' %}</a>
                    {% endif %}
                    {% if partners %}
                    <a {% if not home_page %}href=" {% url 'main:home' %}#partners " {% endif %}
                       onclick="scrollToAnchor('partners')" class="nav-link">{% trans 'Наші партнери' %}</a>
                    {% endif %}
                    {% if reviews %}
                    <a {% if not home_page %}href=" {% url 'main:home' %}#feedbacks " {% endif %}
                       onclick="scrollToAnchor('feedbacks')" class="nav-link">{% trans 'Відгуки' %}</a>
                    {% endif %}
                    <a href="{% url 'main:contacts' %}" class="nav-link">{% trans 'Контакти' %}</a>
                </div>
            </div>
            <!--        // todo: Second iteration-->
<!--            <div class="dropdown">-->
<!--                <button class="dropbtn">{% trans 'Технологічна вітка' %}</button>-->
<!--                <div class="dropdown-content">-->
<!--                    <a href="{% url 'main:accessories' %}" class="nav-link">{% trans 'Наше обладнання' %}</a>-->
<!--                    <a href="{% url 'main:certificates' %}" class="nav-link">{% trans 'Наші сертифікати' %}</a>-->
<!--                    <a href="{% url 'main:partners' %}" class="nav-link">{% trans 'Наші партнери' %}</a>-->
<!--                </div>-->
<!--            </div>-->
            <a href="{% url 'main:contacts' %}">{% trans 'Контакти' %}</a>
        </div>
        <div class="lang-panel">
            {% for lang in language.LANGUAGES %}
            {% if lang.0 == language.SELECTEDLANG %}
            <button class="lang {% if lang.0 == request.LANGUAGE_CODE %} active {% endif %}">
                {{ lang.0 }}
            </button>
            {% else %}
            <form action="{% url 'set_language' %}" method="post"> {% csrf_token %}
                {% if language.redirect_to == '/' %}

                {% if  lang.0 == 'uk' %}
                <input name="next" type="hidden" value="{{ language.redirect_to }}"/>
                {% else %}
                <input name="next" type="hidden" value="/{{lang.0}}"/>

                {% endif %}
                {% endif %}
                <input type="hidden" name="language" value="{{ lang.0 }}">
                <button class="lang ">
                    {{ lang.0 }}
                </button>
            </form>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="header-container-mobile">
        <a href="{% url 'main:home' %}">
            <img class="mobile-logo" src="{% static 'images/logo.png' %}">
        </a>
        <div class="menu-button">
            <button id="toggle-header-button">
                <i class="fa fa-bars"></i>
            </button>
        </div>
    </div>
</header>


<div id="mobile-menu" class="mobile-menu-container">
    <div class="close-button-container">
        <button id="close-mobile-menu-button">
            <i class="fa fa-times"></i>
        </button>
    </div>
    <nav class="mobile-navigation">
        <div class="dropdown-mobile-container">
            <div class="dropdown-mobile-button-container">
                <button class="dropbtn-mobile">{% trans 'Послуги' %}</button>
                <i class="fa fa-chevron-down"></i>
                <i class="fa fa-chevron-up"></i>
            </div>
            <div class="dropdown-mobile-content">
                <a href="{% url 'main:gen_test' %}" class="nav-link">{% trans 'Генетичні тести' %}</a>
                <!--                <a href="#" class="nav-link">{% trans 'Інше' %}</a>-->
            </div>
        </div>
        <div class="dropdown-mobile-container">
            <div class="dropdown-mobile-button-container">
                <button class="dropbtn-mobile">{% trans 'Про нас' %}</button>
                <i class="fa fa-chevron-down"></i>
                <i class="fa fa-chevron-up"></i>
            </div>
            <div class="dropdown-mobile-content">
                <a {% if not home_page %} href=" {% url 'main:home' %}#service " {% endif %}
                   onclick="scrollToAnchor('service')" class="nav-link">{% trans 'Наші послуги' %}</a>
                <a {% if not home_page %} href=" {% url 'main:home' %}#about-us " {% endif %}
                   onclick="scrollToAnchor('about-us')" class="nav-link">{% trans 'Про нас' %}</a>
                <a {% if not home_page %} href="{% url 'main:home' %}#team " {% endif %}
                   onclick="scrollToAnchor('team')" class="nav-link">{% trans 'Наша команда' %}</a>
                {% if acc %}
                <a {% if not home_page %}href=" {% url 'main:home' %}#accessories " {% endif %}
                   onclick="scrollToAnchor('accessories')" class="nav-link">{% trans 'Наше обладнання' %}</a>
                {% endif %}

                {% if license %}
                <a {% if not home_page %}href=" {% url 'main:home' %}#certificates " {% endif %}
                   onclick="scrollToAnchor('certificates')" class="nav-link">{% trans 'Наші сертифікати' %}</a>
                {% endif %}
                {% if partners %}
                <a {% if not home_page %}href=" {% url 'main:home' %}#partners " {% endif %}
                   onclick="scrollToAnchor('partners')" class="nav-link">{% trans 'Наші партнери' %}</a>
                {% endif %}
                {% if reviews %}
                <a {% if not home_page %}href=" {% url 'main:home' %}#feedbacks " {% endif %}
                   onclick="scrollToAnchor('feedbacks')" class="nav-link">{% trans 'Відгуки' %}</a>
                {% endif %}
                <a href="{% url 'main:contacts' %}" class="nav-link">{% trans 'Контакти' %}</a>
            </div>
        </div>
<!--        &lt;!&ndash;        // todo: Second iteration&ndash;&gt;-->
<!--        <div class="dropdown-mobile-container">-->
<!--            <div class="dropdown-mobile-button-container">-->
<!--                <button class="dropbtn-mobile">{% trans 'Технологічна вітка' %}</button>-->
<!--                <i class="fa fa-chevron-down"></i>-->
<!--                <i class="fa fa-chevron-up"></i>-->
<!--            </div>-->
<!--            <div class="dropdown-mobile-content">-->
<!--                <a href="{% url 'main:accessories' %}" class="nav-link">{% trans 'Наше обладнання' %}</a>-->
<!--                <a href="{% url 'main:certificates' %}" class="nav-link">{% trans 'Наші сертифікати' %}</a>-->
<!--                <a href="{% url 'main:partners' %}" class="nav-link">{% trans 'Наші партнери' %}</a>-->
<!--            </div>-->
<!--        </div>-->
        <div class="mobile-menu-link">
            <a href="{% url 'main:contacts' %}" class="dropbtn-mobile">{% trans 'Контакти' %}</a>
        </div>
    </nav>
    <div class="lang-panel">
        {% for lang in language.LANGUAGES %}
        {% if lang.0 == language.SELECTEDLANG %}
        <button class="lang {% if lang.0 == request.LANGUAGE_CODE %} active {% endif %}">
            {{ lang.0 }}
        </button>
        {% else %}

        <form action="{% url 'set_language' %}" method="post"> {% csrf_token %}

             {% if language.redirect_to == '/' %}

                {% if  lang.0 == 'uk' %}
                <input name="next" type="hidden" value="{{ language.redirect_to }}"/>
                {% else %}
                <input name="next" type="hidden" value="/{{lang.0}}"/>

                {% endif %}
                {% endif %}
            <input type="hidden" name="language" value="{{ lang.0 }}">
            <button class="lang ">
                {{ lang.0 }}
            </button>
        </form>
        {% endif %}
        {% endfor %}
    </div>
</div>